### PR TITLE
Task 3

### PR DESCRIPTION
**Pull request by codehack04**

### CODE REVIEW

**Review by Anubhcv — CHANGES_REQUESTED** [review]
Add a screenshot of your webpage.

**Comment by codehack04** [comment]
done

**Review by Anubhcv — APPROVED** [review]

**Comment by codehack04** [comment]
task 2 web development done

**Review by Anubhcv — CHANGES_REQUESTED** [review]
Review your task, you haven't uploaded your task 2 files.

**Comment by codehack04** [comment]
task 2 done

**Review by Anubhcv — APPROVED** [review]

**Pull request merged**
