### PR TITLE
task1

### PR DESCRIPTION
**Pull request by slothracing**
https://slothracing.github.io/html/

### CODE REVIEW

**Review by chandrasekhar2039 — CHANGES_REQUESTED** [review]
Remove the changes you made in README.md file

**Review by chandrasekhar2039 — APPROVED** [review]

**Comment by slothracing** [comment]
task 2 completed

**Review by Anubhcv — CHANGES_REQUESTED** [review]
Review your task, you haven't uploaded your task 2 files.

**Comment by slothracing** [comment]
done bhaiya

**Review by Anubhcv — CHANGES_REQUESTED** [review]
You were supposed to create a folder of your name and upload your files inside it in the Task submission folder, fix it.

**Comment by slothracing** [comment]
task 2

**Review by Anubhcv — APPROVED** [review]

**Pull request merged**
