### PR TITLE
Webpage Task-1 & Task-2 Completed

### PR DESCRIPTION
**Pull request by LalitKumar-2001**
https://lalitkumar-2001.github.io/WebDev-Enigma/

### CODE REVIEW

**Review by Anubhcv — CHANGES_REQUESTED** [review]
You have deleted existing files in Web Development/Task-1/Task submission, add them back and you have uploaded your files as a submodule remove it and upload the files as mentioned in task.

**Comment by LalitKumar-2001** [comment]
Submodule removed and task done.

**Review by Anubhcv — CHANGES_REQUESTED** [review]
You haven't uploaded your task 2 files.

**Comment by LalitKumar-2001** [comment]
I have uploaded the files in Task-2 Submission Folder. 
Please Check.

**Review by Anubhcv — APPROVED** [review]

**Pull request merged**
