### PR TITLE
Task 3 Completed

### PR DESCRIPTION
**Pull request by CaptainBiswa69**
https://captainbiswa69.github.io/Page/

### CODE REVIEW

**Review by ankush0939 — CHANGES_REQUESTED** [review]
Everything is correct but ur link is to be provided in a txt file placed inside the folder. You have just commented the link in the PR. Add the txt file.

**Comment by CaptainBiswa69** [comment]
Bhaiya i added the txt file.

**Review by Anubhcv — CHANGES_REQUESTED** [review]
Review your task you have created your folder in the wrong directory.

**Comment by CaptainBiswa69** [comment]
Bhaiya  i have changed the directory.

**Review by Anubhcv — APPROVED** [review]

**Comment by CaptainBiswa69** [comment]
Task 2 Completed.Updated the page.

**Review by Anubhcv — APPROVED** [review]

**Pull request merged**
