### PR TITLE
Task 1

### PR DESCRIPTION
**Pull request by Sneha247**

### CODE REVIEW

**Review by Anubhcv — CHANGES_REQUESTED** [review]
Review your task. It does not follow the naming convention.

**Comment by Sneha247** [comment]
How to do that ..l.don't know

**Comment by chandrasekhar2039** [comment]
just go through the[ instructions](https://github.com/EnigmaVSSUT/Induction-2021/tree/main/Open%20Source/Git1#problem-statement) once again.

**Review by Anubhcv — CHANGES_REQUESTED** [review]
You can close this pr since both of your tasks been approved in different prs.

**Comment by ankush0939** [comment]
Tasks already merged

**Pull request closed without merging**
