### PR TITLE
WEV_DEV TASK_1 & TASK_2

### PR DESCRIPTION
**Pull request by SOMANATH-2039**
TASK_1 & TASK_2 completed

### CODE REVIEW

**Review by Anubhcv — CHANGES_REQUESTED** [review]
Review your task, your webpage url is not working.

**Comment by SOMANATH-2039** [comment]
Task_1 and Task_2 completed

**Review by Anubhcv — CHANGES_REQUESTED** [review]
Review your task, you haven't uploaded your task 2 files.

**Comment by Anubhcv** [comment]
Your task 1 is completedx

**Review by Anubhcv — CHANGES_REQUESTED** [review]
You have uploaded an extra file(README.md) in Web Development/Task-2/Task submission/Somanath Singh/ remove it and commit again.

**Review by Anubhcv — APPROVED** [review]

**Pull request merged**
