### PR TITLE
Rajat_Kumar_Nayak-031-WEB-D-TASK1

### PR DESCRIPTION
**Pull request by rajat-gith**
https://rajat-gith.github.io/WEB-D/

### CODE REVIEW

**Review by ankush0939 — APPROVED** [review]
Your Instagram link is incorrect

**Comment by rajat-gith** [comment]
My new link is:-
"https://rajat-gith.github.io/WEB-3/"

**Comment by rajat-gith** [comment]
My new link is:-"https://rajat-gith.github.io/WEB-3/"
TASK-2 OF WEB-DEVELOPMENT COMPLETED

**Review by Anubhcv — CHANGES_REQUESTED** [review]
Review your task-2, it doesn't follow the naming convention.

**Comment by rajat-gith** [comment]
Which naming convention?

**Comment by Anubhcv** [comment]
> Which naming convention?

Your task-2 folder is named as TASK2, it should be your name.

**Comment by rajat-gith** [comment]
I have changed the file name. Kindly review it
Url="https://rajat-gith.github.io/WEB-3/"

**Review by Anubhcv — APPROVED** [review]

**Pull request merged**
