### PR TITLE
1 and 2 tasks

### PR DESCRIPTION
**Pull request by omsatpathy**

### CODE REVIEW

**Review by ankush0939 — COMMENTED** [review]
Remove the submodule from webDevelopment task 1 submission and add a folder by ur name with all the required files.

**Review by ankush0939 — CHANGES_REQUESTED** [review]
Remove the submodule from webDevelopment task 1 submission and add a folder by ur name with all the required files.

**Comment by omsatpathy** [comment]
Tasks 1and2

**Review by Anubhcv — CHANGES_REQUESTED** [review]
Review your task, the submodule is still there.

**Pull request closed without merging**
