### PR TITLE
# Task 1 done

### PR DESCRIPTION
**Pull request by harshranjan63**
This folder contains both type i.e. .py type and .ipynb type

### CODE REVIEW

**Review by Anubhcv — CHANGES_REQUESTED** [review]
Replace the .py files with .ipynb files and remove the .ipynb_checkpoints folder.

**Comment by harshranjan63** [comment]
I have updated my task 1 kindly check!

**Review by ankush0939 — CHANGES_REQUESTED** [review]
Remove the VS Code configuration folder (.vscode)

**Comment by harshranjan63** [comment]
#task 1 update 2

**Review by Anubhcv — APPROVED** [review]

**Pull request merged**
