### PR TITLE
Task 1 python

### PR DESCRIPTION
**Pull request by nikhil822**

### CODE REVIEW

**Review by Anubhcv — CHANGES_REQUESTED** [review]
Review your task you have uploaded your files in the wrong directory.

**Review by Anubhcv — CHANGES_REQUESTED** [review]
You were supposed to create a folder of your name and upload your files inside it in the Task submission folder, fix it

**Comment by Anubhcv** [comment]
leave a comment after you commit the changes

**Comment by nikhil822** [comment]
completed

**Review by Anubhcv — APPROVED** [review]

**Pull request merged**
