### PR TITLE
Task 3 completed

### PR DESCRIPTION
**Pull request by Adyasha28**
https://adyasha28.github.io/About-me/

### CODE REVIEW

**Review by chandrasekhar2039 — CHANGES_REQUESTED** [review]
you have messed up the structure of the repo. Fix it.

**Comment by Adyasha28** [comment]
> you have messed up the structure of the repo. Fix it.



> you have messed up the structure of the repo. Fix it.

bhaiya messed up the structure means?!

**Comment by chandrasekhar2039** [comment]
> bhaiya messed up the structure means?!

inside /Open Source/Git2/ you have placed unwanted folders. Remove those.

**Comment by Adyasha28** [comment]
I tried to revert the unwanted files... hope it worked

**Review by chandrasekhar2039 — CHANGES_REQUESTED** [review]
Remove the submodule that you have added

**Review by chandrasekhar2039 — APPROVED** [review]

**Comment by Adyasha28** [comment]
theme switcher webpage added

**Review by Anubhcv — APPROVED** [review]

**Pull request merged**
