### PR TITLE
#Task 2 Completed 

### PR DESCRIPTION
**Pull request by harshranjan63**

### CODE REVIEW

**Review by gouravcyber — CHANGES_REQUESTED** [review]
Update your local repo to the upstream repo and meet the task objective.

**Comment by harshranjan63** [comment]
local repo updated

**Comment by gouravcyber** [comment]
> Local repo updated Have a look on it!

Update your forked repo to  the commits made in main repo ,then make a commit meeting your required task objectives.

**Comment by gouravcyber** [comment]
Still your PR does not meet the task objectives ,your forked repo is not updated. I suggest you to watch some tutorials regarding this and do a bit of research.

**Comment by harshranjan63** [comment]
Did The Updatation Of the forded repo

**Comment by gouravcyber** [comment]
You have updated your forked repo but missed the other part of your task ,add the jpg file and submit the PR

**Review by gouravcyber — APPROVED** [review]
Update your local repo to the upstream repo.

**Review by gouravcyber — APPROVED** [review]

**Pull request merged**
