### PR TITLE
INDUCTION TASK- 2

### PR DESCRIPTION
**Pull request by swapnil-092**
Task 2 - Update the local repo.

### CODE REVIEW

**Review by gouravcyber — CHANGES_REQUESTED** [review]
Your PR does not satisfy the task objectives. Check it again

**Comment by swapnil-092** [comment]
> Your PR does not satisfy the task objectives. Check it again

What is the fault, can you point it out?

**Comment by gouravcyber** [comment]
> > Your PR does not satisfy the task objectives. Check it again
> 
> What is the fault, can you point it out?

Your forked repo is not updated.

**Comment by swapnil-092** [comment]
> > > Your PR does not satisfy the task objectives. Check it again
> > 
> > 
> > What is the fault, can you point it out?
> 
> Your forked repo is not updated.

Is my repo updated??

**Comment by gouravcyber** [comment]
> > > > Your PR does not satisfy the task objectives. Check it again
> > > 
> > > 
> > > What is the fault, can you point it out?
> > 
> > 
> > Your forked repo is not updated.
> 
> Is my repo updated??

No your forked repo is not updated .

**Pull request closed without merging**
