### PR TITLE
Induction Task 1&2

### PR DESCRIPTION
**Pull request by knowtheunknowns**
Induction Task 1

By Adarsh Kumar Goswami

### CODE REVIEW

**Comment by knowtheunknowns** [comment]
Induction Task 2 updated.

**Review by Anubhcv — CHANGES_REQUESTED** [review]
Review task-2. It doesn't follow the required objectives.

**Comment by knowtheunknowns** [comment]
Task 2 checked and updated.

> Review task-2. It doesn't follow the required objectives.

**Review by Anubhcv — CHANGES_REQUESTED** [review]
Review your task. You have pushed extra files.

**Comment by knowtheunknowns** [comment]
> Review your task. You have pushed extra files.

Extra files removed. Kindy plz review again.

**Review by Anubhcv — APPROVED** [review]

**Pull request merged**
