### PR TITLE
Task-3

### PR DESCRIPTION
**Pull request by srr2k21**
https://srr2k21.github.io/my-web/

### CODE REVIEW

**Review by Anubhcv — APPROVED** [review]

**Comment by srr2k21** [comment]
completed Task-2 .
Link-https://srr2k21.github.io/my-web/

**Review by Anubhcv — CHANGES_REQUESTED** [review]
Review your task, you haven't uploaded your task 2 files.

**Comment by srr2k21** [comment]
Now the files are added.

**Review by Anubhcv — CHANGES_REQUESTED** [review]
The url to your task-2 webpage is incorrect, fix it and commit again.

**Comment by srr2k21** [comment]
Previously I  just added the firefox link. Now I added the Google link . Sorry for the Mistake.

**Review by Anubhcv — APPROVED** [review]

**Pull request merged**
